Resources:
  AttachmentsBucket:
    Type: AWS::s3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
            MaxAge: 3000

Outputs:
  AttachmentsBucketName:
    Value:
      Ref: AttachmentsBucket
